using System.Text;
using System.Text.Json;
using System.Text.Json.Nodes;
using IL.Core.Infrastructure;
using IL.Core.Ilp;
using IL.Core.Models;
using IL.Core.Projects;
namespace IL.Core.Mcp;

public sealed class AppPrivateApiService(CourseProjectStore store,string? libraryDirectory=null)
{
    public Action? ProjectChanged {get;set;}
    public Action<string>? OpenProject {get;set;}
    public Func<CourseProject,Task<CourseProject>>? StartAsr {get;set;}
    public Action<CourseProject>? TranscriptReplacing {get;set;}
    public Action? LibraryChanged {get;set;}
    public Func<CourseProject,string,Task<string>>? ExportStandalone {get;set;}
    private static readonly JsonSerializerOptions JsonOptions=new(){PropertyNamingPolicy=JsonNamingPolicy.CamelCase};
    private static JsonObject Json(object value)=>JsonSerializer.SerializeToNode(value,JsonOptions)!.AsObject();
    private static AppPrivateApiException Fail(string code,string text)=>new(code,text);
    private static string? Optional(JsonObject j,string key)=>j[key] is JsonValue v&&v.TryGetValue<string>(out var s)&&!string.IsNullOrWhiteSpace(s)?s.Trim():null;
    private static string Required(JsonObject j,string key)=>Optional(j,key)??throw Fail("invalid_parameters",key+" 不能为空");
    private static bool Number(JsonValue v,out double value) { if(v.TryGetValue<double>(out value))return true; if(v.TryGetValue<int>(out var i)){value=i;return true;} if(v.TryGetValue<long>(out var l)){value=l;return true;} return false; }
    private static int Index(JsonObject j,string key,int? fallback=null,int minimum=0){if(j[key] is null&&fallback!=null)return fallback.Value;if(j[key] is not JsonValue v||!Number(v,out var value)||!double.IsFinite(value)||value<minimum||value>int.MaxValue)throw Fail("invalid_parameters",key+" 必须是有效整数");return (int)Math.Round(value,MidpointRounding.AwayFromZero);}
    private static int[] Indexes(JsonNode? value,string code="invalid_questions") {if(value is not JsonArray a)throw Fail(code,"索引必须是数组");var indexes=a.Select(v=>v is JsonValue n&&Number(n,out var d)&&d>=0&&d<=int.MaxValue?(int)Math.Round(d,MidpointRounding.AwayFromZero):-1).ToArray();if(indexes.Any(i=>i<0)||indexes.Distinct().Count()!=indexes.Length)throw Fail(code,"索引无效或重复");return indexes.Order().ToArray();}
    private static string[] Options(JsonNode? value) {if(value is null)return [];if(value is not JsonArray a||a.Any(x=>x is not JsonValue v||!v.TryGetValue<string>(out _)))throw Fail("invalid_options","选项必须是字符串数组");return a.Select(x=>x!.GetValue<string>().Trim()).ToArray();}
    private static int? Answer(JsonNode? value,string[] options) {if(value is null)return null;if(value is not JsonValue v||!v.TryGetValue<int>(out var i)||i<0||i>=options.Length)throw Fail("invalid_answer","答案索引必须对应已有选项");return i;}
    private async Task<CourseProject> RequireAsync(JsonObject args)=>await RequireAsync(Required(args,"projectId"));
    private async Task<CourseProject> RequireAsync(string id)=>(await store.LoadAllAsync()).FirstOrDefault(p=>p.Id==id)??throw Fail("project_not_found","找不到项目："+id);
    private async Task<CourseProject> SaveAsync(CourseProject p){await store.SaveAsync(p);ProjectChanged?.Invoke();return p;}
    private static object Summary(CourseProject p)=>new {id=p.Id,title=p.Title,step=p.Step.ToString().ToLowerInvariant(),hasAudio=p.HasAudio,hasTranscript=p.HasTranscript,audioPath=p.AudioPath,durationMs=p.AudioDuration?.TotalMilliseconds,packageUuid=p.PackageUuid,packageVersion=p.PackageVersion,questionPlanPending=p.AutoQuestionPlanDeferred&&p.HasTranscript&&!p.AutomaticQuestionPlanApplied,updatedAt=p.UpdatedAt};
    private static IReadOnlyList<SrtCue> Cues(CourseProject p){if(!p.HasTranscript)throw Fail("transcript_required","项目尚无字幕");try{return SrtParser.Parse(Encoding.UTF8.GetBytes(p.Transcript),p.AudioDuration??TimeSpan.FromDays(7));}catch(IlpException e){throw Fail("invalid_srt",e.Message);}}
    private sealed record Page(int Offset,int Limit,int Total){public int End=>Math.Min(Total,Offset+Limit);public object ToJson()=>new{offset=Offset,limit=Limit,returned=End-Offset,total=Total,hasMore=End<Total};}
    private static Page Slice(JsonObject j,int total,bool text=false) {var offset=Index(j,j.ContainsKey("offset")?"offset":"cueOffset",0);var key=j.ContainsKey("limit")?"limit":"cueLimit";var limit=Index(j,key,text?12000:Math.Max(1,total),1);return new(Math.Min(offset,total),j.ContainsKey(key)?Math.Clamp(limit,1,text?50000:500):text?12000:total,total);}
    private static object Words(string text)=>LessonTextTokenizer.Tokenize(text).Where(x=>x.IsWord).Select(x=>new{index=x.WordIndex,text=x.Text}).ToArray();
    private static object Cue(IReadOnlyList<SrtCue> cues,SrtTranscriptStructure structure,int index)=>new{index,startMs=cues[index].Start.TotalMilliseconds,endMs=cues[index].End.TotalMilliseconds,text=cues[index].Text,sectionIndex=structure.SectionIndexForCue(index),isMarker=structure.MarkerCueIndexes.Contains(index),words=Words(cues[index].Text)};
    private static object Materials(CourseProject p)=>p.Exercises.EffectiveMaterials.Select(m=>new{id=m.Id,prompt=m.Prompt,cueIndexes=m.CueIndexes,repeatedCueIndexes=m.RepeatedCueIndexes,leadInCueIndexes=m.LeadInCueIndexes,questionIds=m.QuestionIds,questions=p.Exercises.QuestionsForMaterial(m).Select(q=>new{id=q.Id,number=q.Number,title=q.Title,options=q.Options,answerIndex=q.AnswerIndex})});
    public async Task<object?> DispatchAsync(string method,JsonObject args)
    {
        switch(method)
        {
            case "app.status":return new{ready=true,privateProtocolVersion=1};
            case "agent.connect":return new{@event="Agent",connected=true};
            case "agent.disconnect":return new{@event="User",connected=false};
            case "text.tokenize":var text=Required(args,"text");return new{text,words=Words(text)};
            case "projects.list":return (await store.LoadAllAsync()).Select(Summary).ToArray();
            case "projects.create":return await CreateAsync(args);
            case "projects.get":return await GetAsync(args);
            case "projects.delete":var deleting=await RequireAsync(args);await store.DeleteAsync(deleting.Id);ProjectChanged?.Invoke();return new{projectId=deleting.Id,deleted=true};
            case "projects.open":var opened=await RequireAsync(args);OpenProject?.Invoke(opened.Id);return new{projectId=opened.Id,opened=true};
            case "projects.importMedia":var media=Required(args,"mediaPath");ValidateAudio(media);return Summary(await SaveAsync(await store.BindAudioAsync(await RequireAsync(args),media)));
            case "projects.importExamDocument":try{var doc=await store.ImportExamDocumentAsync(await RequireAsync(args),Required(args,"documentPath"));ProjectChanged?.Invoke();return Exam(doc);}catch(CourseProjectDocumentException e){throw Fail("invalid_docx",e.Message);}
            case "projects.readExamText":var exam=await store.ReadExamDocumentAsync(await RequireAsync(args))??throw Fail("exam_required","项目尚未导入 DOCX 试卷");var response=Json(Exam(exam));if(args.ContainsKey("offset")||args.ContainsKey("limit")){var page=Slice(args,exam.Text.Length,true);response["text"]=exam.Text[page.Offset..page.End];response["textPage"]=JsonSerializer.SerializeToNode(page.ToJson());}return response;
            case "projects.importText":return await ImportTextAsync(args);
            case "projects.readText":return await ReadTextAsync(args);
            case "projects.startAsr":if(StartAsr==null)throw Fail("asr_unavailable","当前应用未开放转写接口");var asr=await RequireAsync(args);if(!asr.HasAudio)throw Fail("audio_required","项目尚未绑定音频");var started=await StartAsr(asr);ProjectChanged?.Invoke();return Summary(started);
            case "projects.importSrt":return await ImportSrtAsync(args);
            case "projects.readSrt":var p=await RequireAsync(args);var cues=Cues(p);var structure=SrtTranscriptStructure.FromCues(cues);var slice=Slice(args,cues.Count);var read=new JsonObject{["projectId"]=p.Id,["cues"]=JsonSerializer.SerializeToNode(Enumerable.Range(slice.Offset,slice.End-slice.Offset).Select(i=>Cue(cues,structure,i))),["cuePage"]=JsonSerializer.SerializeToNode(slice.ToJson())};if(args["includeSrt"]?.ToString()=="true")read["srt"]=p.Transcript;return read;
            case "projects.setCueText":return await SetCueTextAsync(args);
            case "projects.autoPlanQuestions":var planning=await RequireAsync(args);if(planning.Exercises.Questions.Count>0)throw Fail("question_plan_exists","项目已有题目；请使用 apply_question_plan 调整题目");var planned=SrtQuestionPlanner.Plan(Cues(planning),planning.Exercises.ClozeWordIndexes);var latest=await RequireAsync(planning.Id);if(latest.UpdatedAt!=planning.UpdatedAt||latest.Transcript!=planning.Transcript)throw Fail("project_changed","工程已变化，请重新读取");await SaveQuestionsAsync(latest,planned.Materials,planned.Questions);return new{projectId=planning.Id,materialCount=planned.Materials.Count,questionCount=planned.Questions.Count};
            case "projects.applyQuestionPlan":return await ApplyQuestionsAsync(args);
            case "projects.addGroup":return await AddGroupAsync(args);
            case "projects.editGroup":return await EditGroupAsync(args);
            case "projects.deleteGroup":return await DeleteGroupAsync(args);
            case "projects.applyClozePlan":return await ApplyClozeAsync(args,false);
            case "projects.setCloze":return await ApplyClozeAsync(args,true);
            case "projects.validate":return Validate(await RequireAsync(args));
            case "projects.addToLibrary":return await DeliverAsync(args,true);
            case "projects.exportIlp":return await DeliverAsync(args,false);
            case "projects.exportStandalone":return await StandaloneAsync(args);
            default:throw Fail("method_not_found","未知方法："+method);
        }
    }
    private static void ValidateAudio(string path){if(!File.Exists(path))throw Fail("file_not_found","找不到指定音频");if(!IlpManifest.SupportedAudioExtensions.Contains(Path.GetExtension(path).TrimStart('.').ToLowerInvariant()))throw Fail("unsupported_audio","音频格式不受支持");}
    private async Task<object> CreateAsync(JsonObject args){var audio=Optional(args,"audioPath");if(audio!=null)ValidateAudio(audio);var p=await store.CreateAsync(audio);if(Optional(args,"title") is{} title)p=await SaveAsync(p with{Title=title});else ProjectChanged?.Invoke();return Summary(p);}
    private async Task<object> GetAsync(JsonObject args)
    {
        var p=await RequireAsync(args);var j=Json(Summary(p));var supported=new[]{"examDocument","sourceDocuments","cues","sections","materials","questions","cloze"};HashSet<string>? fields=null;if(args["fields"]!=null){if(args["fields"] is not JsonArray raw||raw.Any(x=>x is not JsonValue v||!v.TryGetValue<string>(out var s)||!supported.Contains(s)))throw Fail("invalid_parameters","fields 包含不支持的字段");fields=raw.Select(x=>x!.GetValue<string>()).ToHashSet();}bool Includes(string field)=>fields==null||fields.Contains(field);
        if(Includes("examDocument")){var doc=await store.ReadExamDocumentAsync(p);j["examDocument"]=doc is null?null:Json(new{sourceName=doc.SourceName,textPath=doc.TextPath,sha256=doc.Sha256,paragraphCount=doc.ParagraphCount,tableCount=doc.TableCount});}if(Includes("sourceDocuments"))j["sourceDocuments"]=await SourceDocumentsAsync(p.Id);
        if(!p.HasTranscript){foreach(var field in new[]{"cues","sections","materials","questions"})if(Includes(field))j[field]=new JsonArray();if(Includes("cloze"))j["cloze"]=new JsonObject();return j;}
        try{var cues=Cues(p);var structure=SrtTranscriptStructure.FromCues(cues);if(Includes("cues")){var page=Slice(args,cues.Count);j["cues"]=JsonSerializer.SerializeToNode(Enumerable.Range(page.Offset,page.End-page.Offset).Select(i=>Cue(cues,structure,i)));j["cuePage"]=JsonSerializer.SerializeToNode(page.ToJson());}if(Includes("sections"))j["sections"]=JsonSerializer.SerializeToNode(structure.Sections.Select((s,i)=>new{index=i,label=s.Label,cueIndexes=s.CueIndexes}));if(Includes("questions"))j["questions"]=JsonSerializer.SerializeToNode(p.Exercises.Questions,JsonOptions);if(Includes("materials"))j["materials"]=JsonSerializer.SerializeToNode(Materials(p),JsonOptions);if(Includes("cloze"))j["cloze"]=JsonSerializer.SerializeToNode(p.Exercises.ClozeWordIndexes);}catch(AppPrivateApiException e){j["transcriptError"]=e.Message;}return j;
    }
    private static object Exam(CourseProjectExamDocument d)=>new{projectId=d.Project.Id,sourceName=d.SourceName,documentPath=d.DocumentPath,textPath=d.TextPath,text=d.Text,sha256=d.Sha256,paragraphCount=d.ParagraphCount,tableCount=d.TableCount};
    private string Sources(string id)=>Path.Combine(store.RootDirectory,id,"sources");
    private async Task<JsonObject> SourceDocumentsAsync(string id){var j=new JsonObject();foreach(var role in new[]{"exam","reference"}){var path=Path.Combine(Sources(id),role+".json");if(File.Exists(path)){try{j[role]=JsonNode.Parse(await File.ReadAllTextAsync(path));}catch(JsonException){}}}return j;}
    private static string Role(JsonObject args){var role=Required(args,"role");if(role is not ("exam" or "reference"))throw Fail("invalid_role","role 必须是 exam 或 reference");return role;}
    private async Task<object> ImportTextAsync(JsonObject args)
    {
        var p=await RequireAsync(args);var role=Role(args);var textPath=Required(args,"textPath");if(!File.Exists(textPath))throw Fail("file_not_found","找不到转换后的 TXT");string content;try{content=await File.ReadAllTextAsync(textPath,new UTF8Encoding(false,true));}catch(DecoderFallbackException){throw Fail("invalid_text","TXT 必须使用 UTF-8");}if(string.IsNullOrWhiteSpace(content))throw Fail("invalid_text","转换后的文本为空");var source=Optional(args,"sourcePath");if(source!=null){if(!File.Exists(source))throw Fail("file_not_found","找不到原始文档");if(Path.GetExtension(source).ToLowerInvariant() is not (".pdf" or ".docx"))throw Fail("invalid_document","原始文档必须是 DOCX 或 PDF");}var folder=Sources(p.Id);Directory.CreateDirectory(folder);var output=Path.Combine(folder,role+".txt");if(source!=null)File.Copy(source,Path.Combine(folder,role+Path.GetExtension(source).ToLowerInvariant()),true);await File.WriteAllTextAsync(output,content);var metadata=new{role,sourceName=source is null?null:Path.GetFileName(source),textPath=output,importedAt=DateTimeOffset.Now,textLength=content.Length};await File.WriteAllTextAsync(Path.Combine(folder,role+".json"),JsonSerializer.Serialize(metadata));await SaveAsync(p);var result=Json(metadata);result["projectId"]=p.Id;return result;
    }
    private async Task<object> ReadTextAsync(JsonObject args){var p=await RequireAsync(args);var role=Role(args);var path=Path.Combine(Sources(p.Id),role+".txt");if(!File.Exists(path))throw Fail("document_required","项目尚无该文档文本");var text=await File.ReadAllTextAsync(path);var page=Slice(args,text.Length,true);return new{projectId=p.Id,role,text=text[page.Offset..page.End],textPage=page.ToJson()};}
    private static LessonExercises RetainCloze(LessonExercises e,IReadOnlyList<SrtCue> cues)=>new(e.EffectiveMaterials,e.Questions,e.ClozeWordIndexes.Where(x=>x.Key>=0&&x.Key<cues.Count).Select(x=>new{Cue=x.Key,Words=x.Value.Where(i=>i>=0&&i<LessonTextTokenizer.Tokenize(cues[x.Key].Text).Count(t=>t.IsWord)).ToArray()}).Where(x=>x.Words.Length>0).ToDictionary(x=>x.Cue,x=>x.Words));
    private async Task<object> ImportSrtAsync(JsonObject args)
    {
        var p=await RequireAsync(args);if(!p.HasAudio)throw Fail("audio_required","项目尚未绑定音频");var path=Required(args,"srtPath");if(!File.Exists(path))throw Fail("file_not_found","找不到指定 SRT");var transcript=await File.ReadAllTextAsync(path);var imported=Cues(p with{Transcript=transcript});var mode=Optional(args,"mode")??"auto";if(mode is not ("auto" or "merge" or "replace"))throw Fail("invalid_parameters","mode 必须是 auto、merge 或 replace");bool same=false;try{var old=Cues(p);same=old.Count==imported.Count&&old.Zip(imported).All(pair=>pair.First.Start==pair.Second.Start&&pair.First.End==pair.Second.End);}catch(AppPrivateApiException){}if(mode=="merge"&&!same)throw Fail("timeline_mismatch","merge 模式要求 cue 数量和时间轴与当前字幕一致");var preserve=mode=="merge"||(mode=="auto"&&same);var exercises=preserve?RetainCloze(p.Exercises,imported):LessonExercises.Empty;TranscriptReplacing?.Invoke(p);var updated=await SaveAsync(p with{Transcript=transcript,TranscriptionJobId=null,Step=CourseProjectStep.Review,ReviewPhase=ReviewPhase.Grouping,Exercises=exercises,AutomaticQuestionPlanApplied=preserve,AutoQuestionPlanDeferred=!preserve});var result=Json(Summary(updated));var before=p.Exercises.ClozeWordIndexes.Sum(x=>x.Value.Length);var after=exercises.ClozeWordIndexes.Sum(x=>x.Value.Length);result["mode"]=preserve?"merge":"replace";result["preserved"]=Json(new{questions=preserve?p.Exercises.Questions.Count:0,cloze=after});result["cleared"]=Json(new{questions=preserve?0:p.Exercises.Questions.Count,cloze=before-after});return result;
    }
    private async Task<object> SetCueTextAsync(JsonObject args){var p=await RequireAsync(args);var index=Index(args,"cueIndex");var text=Required(args,"text");if(text.Contains('\n')||text.Contains('\r')||text.Contains("-->"))throw Fail("invalid_cue_text","字幕文本必须为单行，且不能包含 SRT 时间标记");var cues=Cues(p).ToArray();if(index>=cues.Length)throw Fail("invalid_cue_index","字幕索引超出范围");cues[index]=cues[index] with{Text=text};var exercises=RetainCloze(p.Exercises,cues);TranscriptReplacing?.Invoke(p);await SaveAsync(p with{Transcript=SrtParser.Serialize(cues),TranscriptionJobId=null,Exercises=exercises});return new{projectId=p.Id,cue=Cue(cues,SrtTranscriptStructure.FromCues(cues),index),removedClozeIndexes=(p.Exercises.ClozeWordIndexes.GetValueOrDefault(index)??[]).Except(exercises.ClozeWordIndexes.GetValueOrDefault(index)??[]).Order().ToArray()};}
    private async Task<CourseProject> SaveQuestionsAsync(CourseProject p,IReadOnlyList<LessonMaterial> materials,IReadOnlyList<LessonQuestion> questions){if(questions.Select(q=>q.Number).Distinct().Count()!=questions.Count)throw Fail("duplicate_question_numbers","题号重复");return await SaveAsync(p with{Exercises=new(materials,questions.OrderBy(q=>q.Number).ToArray(),p.Exercises.ClozeWordIndexes),Step=CourseProjectStep.Review,ReviewPhase=ReviewPhase.Grouping,AutomaticQuestionPlanApplied=true,AutoQuestionPlanDeferred=false});}
    private async Task<object> ApplyQuestionsAsync(JsonObject args)
    {
        var p=await RequireAsync(args);var cues=Cues(p);var markers=SrtTranscriptStructure.FromCues(cues).MarkerCueIndexes;var assigned=new HashSet<int>();var materials=new List<LessonMaterial>();var questions=new List<LessonQuestion>();var next=1;var stamp=DateTimeOffset.UtcNow.ToUnixTimeMilliseconds();
        JsonArray plan;if(args["materials"] is JsonArray m)plan=m;else if(args["questions"] is JsonArray legacy)plan=new JsonArray(legacy.Select(x=>x is JsonObject q?(JsonNode)new JsonObject{["cueIndexes"]=q["cueIndexes"]?.DeepClone(),["questions"]=new JsonArray(q.DeepClone())}:x?.DeepClone()).ToArray());else throw Fail("invalid_questions","materials 必须是数组");
        for(var mi=0;mi<plan.Count;mi++)
        {
            var raw=plan[mi] as JsonObject??throw Fail("invalid_questions","听力材料必须是对象");var indexes=Indexes(raw["cueIndexes"]);if(indexes.Length==0||indexes.Any(i=>i>=cues.Count||markers.Contains(i)))throw Fail("invalid_questions","听力材料包含无效字幕索引");if(indexes.Any(i=>!assigned.Add(i)))throw Fail("cue_already_assigned","一个字幕句只能属于一段听力材料");var lead=raw["leadInCueIndexes"] is null?[]:Indexes(raw["leadInCueIndexes"]);if(lead.Any(i=>i>=indexes[0]||!assigned.Add(i)))throw Fail("invalid_questions","提前提示索引无效或已归属其他材料");var repeated=raw["repeatedCueIndexes"] is null?[]:Indexes(raw["repeatedCueIndexes"]);if(repeated.Any(i=>!indexes.Contains(i)))throw Fail("invalid_questions","重复朗读索引必须属于本材料");var rawQuestions=raw["questions"] as JsonArray;if(rawQuestions==null||rawQuestions.Count==0)throw Fail("invalid_questions","听力材料没有小题");var materialId=Optional(raw,"id")??$"material-{stamp}-{mi}";var ids=new List<string>();
            for(var qi=0;qi<rawQuestions.Count;qi++){var q=rawQuestions[qi] as JsonObject??throw Fail("invalid_questions","小题必须是对象");var number=Index(q,"number",next,1);next=number+1;var id=Optional(q,"id")??$"question-{stamp}-{mi}-{qi}";var options=Options(q["options"]);ids.Add(id);questions.Add(new(id,Optional(q,"title")??$"第 {number} 题",indexes,repeated,materialId,number,options,Answer(q["answerIndex"],options)));}
            materials.Add(new(materialId,Optional(raw,"prompt")??"",indexes,repeated,lead,ids));
        }
        await SaveQuestionsAsync(p,materials,questions);return new{projectId=p.Id,materialCount=materials.Count,questionCount=questions.Count,repeatedMaterialCount=materials.Count(m=>m.RepeatedCueIndexes.Count>0)};
    }
    private static int[] GroupCues(CourseProject p,JsonNode? value,string? ignore=null){var cues=Cues(p);var indexes=Indexes(value);var markers=SrtTranscriptStructure.FromCues(cues).MarkerCueIndexes;var assigned=p.Exercises.EffectiveMaterials.Where(m=>m.Id!=ignore).SelectMany(m=>m.CueIndexes.Concat(m.LeadInCueIndexes)).ToHashSet();if(indexes.Length==0||indexes.Any(i=>i>=cues.Count||markers.Contains(i)))throw Fail("invalid_questions","字幕索引无效");if(indexes.Any(assigned.Contains))throw Fail("cue_already_assigned","一个字幕句只能属于一段听力材料");return indexes;}
    private static int[] LeadCues(CourseProject p,JsonNode? value,int[] indexes,string? ignore=null){if(value==null)return [];var lead=Indexes(value);var assigned=p.Exercises.EffectiveMaterials.Where(m=>m.Id!=ignore).SelectMany(m=>m.CueIndexes.Concat(m.LeadInCueIndexes)).ToHashSet();if(lead.Any(i=>i>=indexes[0]||assigned.Contains(i)))throw Fail("invalid_questions","提前提示索引无效或已归属其他材料");return lead;}
    private async Task<object> AddGroupAsync(JsonObject args){var p=await RequireAsync(args);var materials=p.Exercises.EffectiveMaterials.ToList();var questions=p.Exercises.Questions.ToList();var number=Index(args,"number",questions.Count+1,1);var requested=Optional(args,"materialId");var material=materials.FirstOrDefault(m=>m.Id==requested);if(material==null){var indexes=GroupCues(p,args["cueIndexes"]);material=new(requested??"material-"+Guid.NewGuid(),Optional(args,"prompt")??"",indexes,[],LeadCues(p,args["leadInCueIndexes"],indexes),[]);materials.Add(material);}var options=Options(args["options"]);var q=new LessonQuestion("question-"+Guid.NewGuid(),Optional(args,"title")??$"第 {number} 题",material.CueIndexes,material.RepeatedCueIndexes,material.Id,number,options,Answer(args["answerIndex"],options));questions.Add(q);materials[materials.IndexOf(material)]=material with{QuestionIds=material.QuestionIds.Append(q.Id).ToArray()};await SaveQuestionsAsync(p,materials,questions);return new{projectId=p.Id,questionCount=questions.Count,createdGroupId=q.Id,createdMaterialId=material.Id};}
    private async Task<object> EditGroupAsync(JsonObject args)
    {
        var p=await RequireAsync(args);var id=Required(args,"groupId");var questions=p.Exercises.Questions.ToList();var qi=questions.FindIndex(q=>q.Id==id);if(qi<0)throw Fail("group_not_found","找不到指定题目");var q=questions[qi];var materials=p.Exercises.EffectiveMaterials.ToList();var mi=materials.FindIndex(m=>m.QuestionIds.Contains(id));if(mi<0)throw Fail("group_not_found","找不到题目所属听力材料");var material=materials[mi];if(args.ContainsKey("cueIndexes")){var indexes=GroupCues(p,args["cueIndexes"],material.Id);material=material with{CueIndexes=indexes,RepeatedCueIndexes=material.RepeatedCueIndexes.Where(indexes.Contains).ToArray(),LeadInCueIndexes=args.ContainsKey("leadInCueIndexes")?LeadCues(p,args["leadInCueIndexes"],indexes,material.Id):material.LeadInCueIndexes,Prompt=Optional(args,"prompt")??material.Prompt};}else if(args.ContainsKey("leadInCueIndexes"))material=material with{LeadInCueIndexes=LeadCues(p,args["leadInCueIndexes"],material.CueIndexes.ToArray(),material.Id)};materials[mi]=material;for(var i=0;i<questions.Count;i++)if(questions[i].MaterialId==material.Id)questions[i]=questions[i] with{CueIndexes=material.CueIndexes,RepeatedCueIndexes=material.RepeatedCueIndexes};var options=args.ContainsKey("options")?Options(args["options"]):q.Options.ToArray();questions[qi]=questions[qi] with{Title=Optional(args,"title")??q.Title,Number=Index(args,"number",q.Number,1),Options=options,AnswerIndex=args.ContainsKey("answerIndex")?Answer(args["answerIndex"],options):q.AnswerIndex is{} answer&&answer<options.Length?answer:null};await SaveQuestionsAsync(p,materials,questions);return new{projectId=p.Id,questionCount=questions.Count};
    }
    private async Task<object> DeleteGroupAsync(JsonObject args){var p=await RequireAsync(args);var id=Required(args,"groupId");if(!p.Exercises.Questions.Any(q=>q.Id==id))throw Fail("group_not_found","找不到指定题目");var questions=p.Exercises.Questions.Where(q=>q.Id!=id).ToArray();var materials=p.Exercises.EffectiveMaterials.Select(m=>m with{QuestionIds=m.QuestionIds.Where(q=>q!=id).ToArray()}).Where(m=>m.QuestionIds.Count>0).ToArray();await SaveQuestionsAsync(p,materials,questions);return new{projectId=p.Id,questionCount=questions.Length};}
    private async Task<object> ApplyClozeAsync(JsonObject args,bool single)
    {
        var p=await RequireAsync(args);var cues=Cues(p);var cloze=single?p.Exercises.ClozeWordIndexes.ToDictionary(x=>x.Key,x=>x.Value):new Dictionary<int,int[]>();var items=single?new JsonArray(args.DeepClone()):args["items"] as JsonArray??throw Fail("invalid_cloze","items 必须是数组");int last=0;int[] lastWords=[];foreach(var item in items){var raw=item as JsonObject??throw Fail("invalid_cloze","挖空项目格式无效");var cue=Index(raw,"cueIndex");if(cue>=cues.Count)throw Fail("invalid_cloze","字幕索引超出范围");var indexes=Indexes(raw["wordIndexes"],"invalid_cloze");if(indexes.Any(i=>i>=LessonTextTokenizer.Tokenize(cues[cue].Text).Count(x=>x.IsWord)))throw Fail("invalid_cloze","单词索引超出范围");if(indexes.Length==0)cloze.Remove(cue);else cloze[cue]=indexes;last=cue;lastWords=indexes;}await SaveAsync(p with{Exercises=new(p.Exercises.EffectiveMaterials,p.Exercises.Questions,cloze),ReviewPhase=ReviewPhase.Cloze});return single?new{projectId=p.Id,cueIndex=last,wordIndexes=lastWords}:(object)new{projectId=p.Id,clozeCueCount=cloze.Count};
    }
    private static object Validate(CourseProject p){var issues=new List<object>();if(!p.HasAudio)issues.Add(new{code="audio_required",message="项目尚未绑定音频"});if(!p.HasTranscript)issues.Add(new{code="transcript_required",message="项目尚无字幕"});else try{Cues(p);}catch(AppPrivateApiException e){issues.Add(new{code="invalid_srt",message=e.Message});}var numbers=new HashSet<int>();foreach(var q in p.Exercises.Questions){if(!numbers.Add(q.Number))issues.Add(new{code="duplicate_question_numbers",message=$"题号 {q.Number} 重复"});if(q.AnswerIndex is{} a&&(a<0||a>=q.Options.Count))issues.Add(new{code="invalid_answer",message=$"题号 {q.Number} 答案索引无效"});}return new{projectId=p.Id,valid=issues.Count==0,issues};}
    private string ExportPath(string requested,string extension)
    {
        var exports=Path.Combine(AppDirectories.DataDirectory(),"exports");Directory.CreateDirectory(exports);if(string.IsNullOrWhiteSpace(requested)||requested.Split('/','\\').Contains(".."))throw Fail("invalid_export_path","导出路径无效");var target=Path.GetFullPath(Path.IsPathRooted(requested)?requested:Path.Combine(exports,requested));if(!target.EndsWith(extension,StringComparison.OrdinalIgnoreCase))target+=extension;var parent=Path.GetDirectoryName(target)!;if(!Directory.Exists(parent))throw Fail("invalid_export_path","请先创建导出目录");var profile=Environment.GetEnvironmentVariable("USERPROFILE")??Environment.GetEnvironmentVariable("HOME");var allowed=new List<string>{exports};if(profile!=null){allowed.Add(Path.Combine(profile,"Desktop"));allowed.Add(Path.Combine(profile,"Documents"));}string Canonical(string path){var full=Path.GetFullPath(path);var segments=full[Path.GetPathRoot(full)!.Length..].Split(Path.DirectorySeparatorChar);var current=Path.GetPathRoot(full)!;foreach(var segment in segments){current=Path.Combine(current,segment);var info=new DirectoryInfo(current);if(info.Exists&&info.LinkTarget!=null)current=info.ResolveLinkTarget(true)!.FullName;}return current;}var canonical=Canonical(parent);if(File.Exists(target)||!allowed.Where(Directory.Exists).Any(root=>{var relative=Path.GetRelativePath(Canonical(root),canonical);return relative=="."||(!Path.IsPathRooted(relative)&&relative!=".."&&!relative.StartsWith(".."+Path.DirectorySeparatorChar));}))throw Fail("invalid_export_path","仅可导出到桌面、文档或应用导出目录，且文件名不能与现有文件重复");return target;
    }
    private async Task<string> CreateIlpAsync(CourseProject p,string output,int version){if(!p.HasAudio||!p.HasTranscript)throw Fail("project_incomplete","导出前必须绑定音频并准备字幕");var temp=Path.Combine(Path.GetTempPath(),Guid.NewGuid()+".srt");try{await File.WriteAllTextAsync(temp,p.Transcript);await new IlpCreator().CreateAsync(p.Title,p.AudioPath!,temp,output,p.PackageUuid,version,p.AudioDuration,p.Exercises);return output;}finally{if(File.Exists(temp))File.Delete(temp);}}
    private async Task<object> DeliverAsync(JsonObject args,bool add)
    {
        var p=await RequireAsync(args);var version=p.PackageVersion+1;var output=add?Path.Combine(Path.GetTempPath(),Guid.NewGuid()+".ilp"):ExportPath(Required(args,"outputPath"),".ilp");try{await CreateIlpAsync(p,output,version);if(add){var library=libraryDirectory??Path.Combine(AppDirectories.DataDirectory(),"library");var lesson=await new IlpImporter(library).ImportFileAsync(output,true);await SaveAsync(p with{PackageVersion=version,Step=CourseProjectStep.Completed});LibraryChanged?.Invoke();return new{projectId=p.Id,lessonId=lesson.Id,packageUuid=p.PackageUuid,packageVersion=version,addedToPlayback=true};}await SaveAsync(p with{PackageVersion=version,LastExportPath=output,Step=CourseProjectStep.Completed});return new{projectId=p.Id,outputPath=output,packageUuid=p.PackageUuid,packageVersion=version};}catch(IlpException e){throw Fail(add?"publish_failed":"export_failed",e.Message);}finally{if(add&&File.Exists(output))File.Delete(output);}
    }
    private async Task<object> StandaloneAsync(JsonObject args){if(!OperatingSystem.IsWindows())throw Fail("windows_required","独立播放器需要在 Windows 版本中生成");var p=await RequireAsync(args);var output=ExportPath(Required(args,"outputPath"),".exe");if(ExportStandalone==null)throw Fail("export_failed","独立播放器导出组件未就绪");await ExportStandalone(p,output);var version=p.PackageVersion+1;await SaveAsync(p with{PackageVersion=version,LastExportPath=output,Step=CourseProjectStep.Completed});return new{projectId=p.Id,outputPath=output,packageUuid=p.PackageUuid,packageVersion=version};}
}
