<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>WinExe</OutputType><ApplicationIcon>../../assets/app_icon.ico</ApplicationIcon><AssemblyName>lesson_player_launcher</AssemblyName><PublishSingleFile>true</PublishSingleFile><SelfContained>true</SelfContained><EnableCompressionInSingleFile>true</EnableCompressionInSingleFile></PropertyGroup>
</Project>
