using System.Collections.Generic;
namespace IL.App.Views.Dialogs;
internal static class DartIcons
{
    internal static readonly IReadOnlyDictionary<string, int> Glyphs = new Dictionary<string, int>
    {
        ["accept"] = 0xe8fb,
        ["add"] = 0xe710,
        ["back"] = 0xe72b,
        ["cancel"] = 0xe711,
        ["chart"] = 0xe999,
        ["check_mark"] = 0xe73e,
        ["checkbox_composite"] = 0xe73a,
        ["chevron_down"] = 0xe70d,
        ["chevron_left"] = 0xe76b,
        ["chevron_right"] = 0xe76c,
        ["cloud"] = 0xe753,
        ["clock"] = 0xe917,
        ["chrome_close"] = 0xe8bb,
        ["completed"] = 0xe930,
        ["warning"] = 0xe7ba,
        ["color"] = 0xe790,
        ["copy"] = 0xe8c8,
        ["delete"] = 0xe74d,
        ["document"] = 0xe8a5,
        ["download"] = 0xe896,
        ["edit"] = 0xe70f,
        ["edit_create"] = 0xf3c9,
        ["education"] = 0xe7be,
        ["error_badge"] = 0xea39,
        ["folder"] = 0xe8b7,
        ["folder_open"] = 0xe838,
        ["font"] = 0xe8d2,
        ["font_size"] = 0xe8e9,
        ["forward"] = 0xe72a,
        ["global_nav_button"] = 0xe700,
        ["help"] = 0xe897,
        ["info"] = 0xe946,
        ["lock"] = 0xe72e,
        ["music_in_collection"] = 0xe940,
        ["music_note"] = 0xec4f,
        ["open_file"] = 0xe8e5,
        ["open_folder_horizontal"] = 0xed25,
        ["page"] = 0xe7c3,
        ["pause"] = 0xe769,
        ["play"] = 0xe768,
        ["play_solid"] = 0xf5b0,
        ["progress_loop_outer"] = 0xecdf,
        ["refresh"] = 0xe72c,
        ["repeat_all"] = 0xe8ee,
        ["robot"] = 0xe99a,
        ["save"] = 0xe74e,
        ["search"] = 0xe721,
        ["settings"] = 0xe713,
        ["sync"] = 0xe895,
        ["text_document"] = 0xf029,
        ["toggle_right"] = 0xf19f,
        ["upload"] = 0xe898,
    };
}
